version: '3.8'
services:
  api:
    build:
      context: ./trackingapi
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
